### ISSUE TITLE
[BUG] Plugin generates a warning for "temperature" characteristic 

### ISSUE THREAD

**Issue by Cruncher13** [johannrichard/homebridge-dingz#562] opened 2022-12-29 10:54 UTC
I am getting the following Error every few seconds:

This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

 "name": "myStrom Bridge",
            "pollerInterval": 5,
            "motionPoller": false,
            "minStepTiltAngle": 1,
            "autoDiscover": true,
            "devices": [
                {
                    "type": "myStromSwitch",
                    "name": "myStrom Switch 1",
                    "address": "192.168.0.105",
                    "token": "XXX"
                },
                {
                    "type": "myStromSwitch",
                    "name": "myStrom Switch 2",
                    "address": "192.168.0.106",
                    "token": "XXX"

**Comment by johannrichard** [comment] 2022-12-29 13:32
Thanks for bringing this to my attention. I remember having seen this once but couldn't reproduce it so far.  IIRC, it was (only) during startup and until the devices were properly detected. 

I could just stop updating the temperature if it's not been reported yet (e.g. on startup) but we might miss a different problem. A few questions:

- do you (also) have a dingz or just MyStrom Switch devices in place?
- could you enable debug mode (in Homebridge) and check if there is any debug output before the warning, e.g. in the form of `[Switch AAAAA]: Get Characteristic Temperature -> undefinded° C'`

**Comment by Cruncher13** [comment] 2022-12-29 13:47
I only have 2 MySwitch v1 in use. For me it would even be better if I would have an option to disable the Temperature feature.
I already deleted the package again. I will reinstall it and post the debug log here.

**Comment by Cruncher13** [comment] 2022-12-30 13:38
I just reinstalled everything. The bug still exists.

`[12/30/2022, 2:38:04 PM] [homebridge-dingz] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[12/30/2022, 2:38:04 PM] [homebridge-dingz] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentTemperature.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at /homebridge/node_modules/homebridge-dingz/src/myStromSwitchAccessory.ts:140:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/30/2022, 2:38:14 PM] [myStrom] Event -> PlatformEvent.REQUEST_STATE_UPDATE
[12/30/2022, 2:38:14 PM] [myStrom] [Steckdose] GET http://192.168.0.105/report
[12/30/2022, 2:38:14 PM] [myStrom] [Steckdose] 200 OK (GET http://192.168.0.105/report)
[12/30/2022, 2:38:14 PM] [homebridge-dingz] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[12/30/2022, 2:38:14 PM] [homebridge-dingz] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentTemperature.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at /homebridge/node_modules/homebridge-dingz/src/myStromSwitchAccessory.ts:140:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by Cruncher13** [comment] 2022-12-30 13:39
[12/30/2022, 2:38:04 PM] [homebridge-dingz] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[12/30/2022, 2:38:04 PM] [homebridge-dingz] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentTemperature.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at /homebridge/node_modules/homebridge-dingz/src/myStromSwitchAccessory.ts:140:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/30/2022, 2:38:14 PM] [myStrom] Event -> PlatformEvent.REQUEST_STATE_UPDATE
[12/30/2022, 2:38:14 PM] [myStrom] [Steckdose] GET http://192.168.0.105/report
[12/30/2022, 2:38:14 PM] [myStrom] [Steckdose] 200 OK (GET http://192.168.0.105/report)
[12/30/2022, 2:38:14 PM] [homebridge-dingz] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[12/30/2022, 2:38:14 PM] [homebridge-dingz] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentTemperature.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at /homebridge/node_modules/homebridge-dingz/src/myStromSwitchAccessory.ts:140:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by johannrichard** [comment] 2022-12-30 13:51
Thanks for reporting back. For some reason, your v1 Switches are treated as v2 w/ temperature reporting. Would you mind posting the output from http://192.168.0.105/info (don't forget to obfuscate the MAC address when pasting it)?

**Comment by Cruncher13** [comment] 2022-12-30 13:52
Also Apple Home tells me that the switch is not connected even everything is working fine.

I habe iOS 16.2 installed with the Architecture update in place.

**Comment by Cruncher13** [comment] 2022-12-30 13:53
> Thanks for reporting back. For some reason, your v1 Switches are treated as v2 w/ temperature reporting. Would you mind posting the output from http://192.168.0.105/info (don't forget to obfuscate the MAC address when pasting it)?

{
	"version":	"2.68.10",
	"mac":	"XXX",
	"ssid":	"XXX",
	"ip":	"",
	"mask":	"",
	"gateway":	"",
	"dns":	"",
	"static":	false,
	"connected":	true,
	"connectionStatus":	{
		"ntp":	true,
		"dns":	true,
		"connection":	true,
		"handshake":	true,
		"login":	true
	}
}

**Comment by Cruncher13** [comment] 2022-12-30 14:07
<blockquote class="imgur-embed-pub" lang="en" data-id="a/OhzUX69" data-context="false" ><a href="//imgur.com/a/OhzUX69"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by johannrichard** [comment] 2022-12-30 14:16
Thanks a lot. I found the issue. With the introduction of the Zero Switch, the validation of the model changed when deciding whether to add a temperature service or not. Since there are never any valid temperature values, the plugin will return an error, reporting that the switch is not connected. I'll release a new version soon, right now, I'm testing it with my v1/v2 versions. You should get a ping via the release tool.

**Comment by Cruncher13** [comment] 2022-12-30 14:20
you are the best. Thank you for your time and your patience! I am happy I can finally use my v1 switches again in Apple Home.

**Comment by johannrichard** [comment] 2022-12-30 14:36
> you are the best. Thank you for your time and your patience! I am happy I can finally use my v1 switches again in Apple Home.

Thanks to you for reporting this and for your patience. :-) This time, I hope I get it right.

**Comment by Cruncher13** [comment] 2022-12-30 15:24
The error is gone with the new version. But the temperature Sensor is still showing up and shows up as not responding.
Can this be ignored somehow?

**Comment by Cruncher13** [comment] 2022-12-30 15:38
I just reinstalled the plugin (alpha) and installed a new child bridge. Now everything seems to be fine and no temp sensor.
Thank you very much for your very fast and gorgeous help.

**Comment by johannrichard** [comment] 2022-12-30 15:58
Thanks for the feedback and glad to hear you got it working. The temperature service may have been kept around once it was created. I have implemented additional adjustments that should avoid this in the future. Will be released with the next alpha/beta.

**Closed** 2022-12-30 23:10 UTC
Labels: released on @beta, released on @alpha, released
